spring:
  application:
    name: newsapp
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://www.db4free.net:3306/[database]
    username: [username]
    password: [password]

app:
  cors:
    allowed-origins: "*"
logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
